apiVersion: v1
kind: Service
metadata:
  name: api-service-{{port}}
  labels:
    app: api-{{port}}
  namespace: clika
spec:
  type: NodePort
  selector:
    app: api-{{port}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{port}}